### PR TITLE
Keras tutorial image

### PR DESCRIPTION
**Pull request by GilesStrong**
Adding image for keras tutorial

### CODE REVIEW

**Comment by GilesStrong** [comment]
# Issues
Jupyter does not run - need to correct `CMD` or add extra setup. @samuelbernardo do you know what would work? Looking at [run_jupyter](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/run_jupyter.sh) it simply seems to call `jupyter notebook`, but when I try that it I get the error `starting container process caused "exec: \"jupyter notebook --allow-root --notebook-dir=/notebooks\": stat jupyter notebook --allow-root --notebook-dir=/notebooks: no such file or directory": unknown.`

**Comment by samuelbernardolip** [comment]
> # Issues
> Jupyter does not run - need to correct `CMD` or add extra setup. @samuelbernardo do you know what would work? Looking at [run_jupyter](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/run_jupyter.sh) it simply seems to call `jupyter notebook`, but when I try that it I get the error `starting container process caused "exec: \"jupyter notebook --allow-root --notebook-dir=/notebooks\": stat jupyter notebook --allow-root --notebook-dir=/notebooks: no such file or directory": unknown.`

@GilesStrong the image is done following the following user guide for docker:
https://lip-computing.github.io/datascience2019/use_docker.html

The error happened because Tiago told me to map notebook directory from local computer inside docker image, as described in the above page.
So the parameter notebook-dir=/notebooks is forcing the notebooks directory for jupyter in that path, since as default it searches the notebooks at /.
If you prefer a different approach we can define it with a new docker file.

**Comment by Tiagval** [comment]
Hello @GilesStrong ,

As the images are right now the notebook directories need to be mounted in a specific path so that the Jupyter server that is automatically launched can see them. Otherwise people had to start in a shell and load the Jupyter sever by hand (not the end of the world but it is easier in this way).

In your image do you need to give it a notebooks directory as is in this case? Maybe it can work the same way?

**Comment by GilesStrong** [comment]
@Tiagval @samuelbernardolip I don't think it was anything to do with the notebook directory, it was instead the jupyter command which was not found.
I've added some extra configuration steps and now it can work however the URL it displays is not directly clickable and has to be modified:
Screenshot 2019-03-14 at 14 11 47
I'll try and get it to just direct to localhost has normal.

**Comment by samuelbernardolip** [comment]
> @Tiagval @samuelbernardolip I don't think it was anything to do with the notebook directory, it was instead the jupyter command which was not found.

@GilesStrong My test follows the steps I mentioned for docker image. With that I couldn't reproduce the problem with jupyter notebook, only when the directory is not created inside docker. Maybe that cloud be another problem related to docker version you're using...
So if you found the source of the problem just do a push to the repository with the needed changes, so we can test in our environments and see if it works.

> I've added some extra configuration steps and now it can work however the URL it displays is not directly clickable and has to be modified:
> Screenshot 2019-03-14 at 14 11 47
> I'll try and get it to just direct to localhost has normal.

This is what I have when docker starts:

jupyter_notebook

So I think that your issue cloud be related to your docker version.
I'm running Docker version 18.09.2, build 6247962, compiled to GNU/Linux (Ubuntu 18.04).

If you find the solution for the bug you mentioned, just upload the changes for us to test.

**Comment by GilesStrong** [comment]
@samuelbernardolip Thanks for checking, can you confirm this was running the keras_tutorial image? It looks like you were running one of the existing Docker images (2019:cpu-py35), which I also have no problem running.

**Comment by samuelbernardolip** [comment]
@GilesStrong The image 2019:cpu-py35 contains Keras, Tensorflow and GWPY.
I'm using the base image from Datmo but I don't know any further details.
Sorry for my inexperience in keras_tuturial images, but if you need any additional test just give me some more details how to do it. Thanks

**Comment by GilesStrong** [comment]
@samuelbernardolip sorry for the misunderstanding, this pull request adds a new image called [keras_tutorial](https://github.com/LIP-Computing/datascience2019/blob/tutorial/keras_tutorial/Dockerfile) which is the one I'm trying to configure to correctly start jupyter.

**Comment by samuelbernardolip** [comment]
> @samuelbernardolip sorry for the misunderstanding, this pull request adds a new image called [keras_tutorial](https://github.com/LIP-Computing/datascience2019/blob/tutorial/keras_tutorial/Dockerfile) which is the one I'm trying to configure to correctly start jupyter.

Sorry @GilesStrong , I though the problem was with the images already provided.
I'll review that and give you the feedback you asked for.

**Comment by samuelbernardolip** [comment]
> @Tiagval @samuelbernardolip I don't think it was anything to do with the notebook directory, it was instead the jupyter command which was not found.
> I've added some extra configuration steps and now it can work however the URL it displays is not directly clickable and has to be modified:
> Screenshot 2019-03-14 at 14 11 47
> I'll try and get it to just direct to localhost has normal.

This issue related to url appears with localhost and an hash is a bug in tag 0.5 of jupyter that will be corrected on tag 0.6, has detailed in the following merge request:
https://github.com/jupyter/repo2docker/pull/358

So to correct that problem jupyter notebook needs to be downgraded from 5.5  to 5.4.1:
pip3 install --no-cache-dir notebook==5.4.1
https://github.com/jupyter/repo2docker/issues/325

@GilesStrong is there any inconvenient to downgrade jupyter notebook?

**Comment by samuelbernardolip** [comment]
I had to change notebook version as mentioned before and change jupyter ip from 0.0.0.0 to 127.0.0.1.
Even with the previous version of notebook, the installed Jupyter release doesn't associate hostname as expected.

I also remove notebook path parameter from CMD in dockerfile, since it was the reason that jupyter wasn't starting. I realized after a test that jupyter is already in path.
Unfortunately the autotests can't be public in dockerhub, but the output received with docker-compose give a better logging to understand the problems.

If you decide to place the datasets and notebooks outside the docker image, I would suggest to use @Tiagval approach mapping the desired directories from local machine into docker with -v flag. That will need to use the Jupyter notebook directory path parameter that I removed from this dockerfile version.

@GilesStrong please review the image generated by the dockerfile:
jupyter-notebook-keras-tutorial

The autotest is failing in dockerhub because jupyter remains running in the frontend, I have to review how to launch jupyter in test mode, so it stops afterwards. I mention this since as you can view here, in the end of pull requests commands, test to ci/dockercloud (/keras_tutorial) failed in dockerhub.

@GilesStrong if this changes works with your datasets just mark it ready for review to accept the merge request. Dockerhub is already configured to generate the image and publish it when it become available at master branch. The associated tag is cpu-py36-keras_tutorial, but I can change it for what you would prefer.

**Comment by GilesStrong** [comment]
@samuelbernardolip I tried the image after your commits but when I tried to access 127.0.0.1:8888, it said that no data was sent.
In the end I found that setting the ip to 0.0.0.0 displayed the link as clickable and working, and adding back `--notebook-dir=/notebooks` did not cause any problems. It seems it simply was the notebook version.

As it stands, the image runs my notebooks without issue and the link doesn't cause any problems.
I'm running it using `docker run -it -p 8888:8888 -v /Users/giles/cernbox/LIP_DSS_Keras_Tutorial_2019/notebooks:/notebooks keras_tutorial`. Could you or @Tiagval test as well? I'll try on another machine as well. Thanks!

**Comment by samuelbernardolip** [comment]
@GilesStrong The image is working for me with your commit.

**Comment by GilesStrong** [comment]
@samuelbernardolip great, thanks for checking. I'll mark the PR as ready.

**Pull request merged**
