### PR TITLE
Adding tutorial repo and data to image

### PR DESCRIPTION
**Pull request by GilesStrong**
COnfiguring docker image to pull tutorial repo and set up data so can be used purely offline

### CODE REVIEW

**Comment by samuelbernardolip** [comment]
@GilesStrong I tested the image and it's working for me.
As a suggestion to optimize the generated image size, we can merge as much as possible all the RUN calls so layers are reduced in generated image. I can help with that if you agree with this kind of dockerfile optimization.

Not related to this merge request, Nuno Castro ask for a single image for all lessons. Reviewing all requests, I know that they're using cpu-py35 and gpu-py35 images from Datmo.
Do you think we can have your image with the other Datmo images?

**Comment by samuelbernardolip** [comment]
> Not related to this merge request, Nuno Castro ask for a single image for all lessons. Reviewing all requests, I know that they're using cpu-py35 and gpu-py35 images from Datmo.
> Do you think we can have your image with the other Datmo images?

@GilesStrong I will send and email with my proposal for images, notebooks and datasets organization.
Since there are different requirements, there will be 3 different images. I'll propose to place the notebooks and datasets into the desired image.

**Comment by GilesStrong** [comment]
@samuelbernardolip ok, sounds good. I'm just testing whether the image size is affected by splitting the run calls. I'm not sure what you mean by "Do you think we can have your image with the other Datmo images?". The Datmo images are incompatible with my tutorial due to having to configure python to use 3.6.
Also, the tutorial image in this PR will automatically pull my tutorial and the required data, so not further setup should be required for that, I think.

**Comment by GilesStrong** [comment]
@samuelbernardolip I've just updated an image version with the `RUN` call concatenated. The images size reduces slight from 1.9 GB to 1.89 GB. I've also checked it can still run the tutorial correctly and everything is fine.

**Comment by samuelbernardolip** [comment]
> @samuelbernardolip I'm not sure what you mean by "Do you think we can have your image with the other Datmo images?". The Datmo images are incompatible with my tutorial due to having to configure python to use 3.6.

Yes, you're right. I review all the requirements that everyone told me and I think we need at least three independent images. I just sent an email proposing that.

> Also, the tutorial image in this PR will automatically pull my tutorial and the required data, so not further setup should be required for that, I think.

Yes everything is working just as expected with your dockerfile for an offline loading. I also propose the following suggested by @Tiagval for running offline images:
- save images to file
```
docker save "<image>" | gzip > "<image name>.tar.gz"
```
- load images from file
```
gzip < "<image name>.tar.gz" | docker load
```

I'll update the use docker guide with this alternative approach for offline[1].
[1] https://lip-computing.github.io/datascience2019/use_docker.html

**Comment by samuelbernardolip** [comment]
> @samuelbernardolip I've just updated an image version with the `RUN` call concatenated. The images size reduces slight from 1.9 GB to 1.89 GB. I've also checked it can still run the tutorial correctly and everything is fine.

Ok, it seems that it didn't make any difference in size, but it maybe can win in performance with less layering (just following the docker optimization guide).
Since it's working for me I'll accept the pull request.

**Pull request merged**
